version: "3.9"
services:
  web:
    build: .
    entrypoint: ["./entrypoint.sh"]
    command: gunicorn MedQueue.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-medqueue}
      POSTGRES_USER: ${POSTGRES_USER:-medqueue}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-medqueue}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
volumes:
  pgdata:
