services:
  db:
    image: postgres:15-alpine
    container_name: medqueue-db
    environment:
      POSTGRES_DB: medqueue
      POSTGRES_USER: medqueue
      POSTGRES_PASSWORD: medqueue
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U medqueue -d medqueue" ]
      interval: 5s
      timeout: 5s
      retries: 12

  web:
    build: .
    container_name: medqueue-web
    entrypoint: [ "/app/entrypoint.sh" ]
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  redis:
    image: redis:8-alpine
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
